window.addEventListener('error',function(e){var b=document.getElementById('runtimeError');if(b){b.hidden=false;b.textContent='The zoo encountered an error: '+(e.message||'Unknown error');}});
(function(){'use strict';
var $=function(s){return document.querySelector(s)},$$=function(s){return Array.prototype.slice.call(document.querySelectorAll(s))};
var G={stage:'intake',idea:'',promise:'',refuse:'',food:'',misuse:'',kind:'Fleck',name:'',tests:0,fixes:0,done:false,stats:{usefulness:50,appetite:50,contagion:50,control:50,mutation:50}};
var species={
Fleck:{shape:'moth',names:['Umbrella Moth','Pocket Lantern','Softwing'],base:[38,22,26,78,37],body:'Small winged thing',breed:'Slow affectionate imitation',risk:'Low',desc:'Small does not mean worthless. It survives by making one difficult room easier to endure.'},
Hand:{shape:'hound',names:['Copper Hound','Tender Ox','Work Elk'],base:[76,40,36,64,45],body:'Working quadruped',breed:'Through demonstrated usefulness',risk:'Moderate',desc:'It wants to work. The danger is hiding who must feed and repair it.'},
Mirror:{shape:'deer',names:['Glass Stag','Silver Deer','Facebird'],base:[54,60,66,42,65],body:'Reflective social animal',breed:'Through identity and imitation',risk:'High',desc:'It changes what citizens believe their behaviour says about them.'},
Teeth:{shape:'lion',names:['Black Lion','Crown Wolf','Red Judge'],base:[58,78,60,25,72],body:'Ceremonial predator',breed:'By finding enemies',risk:'Severe',desc:'It becomes stronger by taking freedom, dignity, attention or power from something else.'},
Swarm:{shape:'swarm',names:['Choir Flies','Copy Bees','Echo Gnats'],base:[50,65,92,20,82],body:'Many bodies, one intention',breed:'Faster than examination',risk:'Extreme',desc:'Its real habitat is the condition that rewards repetition.'},
Weather:{shape:'storm',names:['Permanent Headwind','Consensus Rain','Bright Storm'],base:[58,72,95,12,88],body:'Atmospheric condition',breed:'By becoming a background assumption',risk:'Catastrophic',desc:'It has stopped behaving like an argument and begun behaving like reality.'},
Burrower:{shape:'beaver',names:['Grey Numberer','Archive Beaver','Pipe Mole'],base:[82,25,18,78,28],body:'Low maintenance animal',breed:'Through standards and routine',risk:'Low but foundational',desc:'The city ignores it until everything depends on work it quietly remembered to do.'}
};
var effects={praise:[3,8,14,-6,5],money:[10,14,9,-8,4],resistance:[-4,5,3,12,9],enemy:[-7,10,17,-13,12],silence:[-2,-6,-15,8,-2]};
var repairs={consent:[-5,-4,0,18,0],transparency:[0,-5,-12,14,0],limit:[-7,0,0,10,-18],appeal:[2,-10,0,18,0],ownership:[0,-4,0,12,9],maintenance:[14,-9,0,7,0]};
var reactions={
praise:{Fleck:'It glows, then hides from the applause.',Hand:'It invents unnecessary work so the praise will continue.',Mirror:'It grows a second face for the audience.',Teeth:'Its mane expands. Admiration feels like permission.',Swarm:'Every clap produces another body.',Weather:'The room fills with certainty.',Burrower:'It ignores everyone and labels a drain.'},
money:{Fleck:'It becomes expensive without becoming more useful.',Hand:'It pulls twice the load and needs three times the feed.',Mirror:'Its reflection improves for whoever is paying.',Teeth:'It learns the difference between prey and customer.',Swarm:'It discovers advertising.',Weather:'The storm gains a sponsor and a permanent season.',Burrower:'It requests a maintenance budget.'},
resistance:{Fleck:'It lands beside the person who refused.',Hand:'It slows down and reveals which tasks matter.',Mirror:'It calls refusal a failure of identity.',Teeth:'It records the names of those who said no.',Swarm:'It turns refusal into content.',Weather:'The dissenting voice becomes hard to hear.',Burrower:'It adds an objection field to the form.'},
enemy:{Fleck:'It does not understand the instruction.',Hand:'It becomes efficient at the wrong task.',Mirror:'Its surface hardens into a uniform.',Teeth:'It finally looks happy.',Swarm:'Every body points the same way.',Weather:'Thunder gives the enemy a chantable name.',Burrower:'It requests a written definition of enemy.'},
silence:{Fleck:'It survives beside one person who needed it.',Hand:'It keeps working until the work is visible.',Mirror:'Its skin dulls. It searches for a camera.',Teeth:'It begins manufacturing a crisis.',Swarm:'Most bodies vanish. A few learn patience.',Weather:'The pressure drops, but the air remembers.',Burrower:'Nothing changes. It was never performing for you.'}
};
function clamp(n){return Math.max(0,Math.min(100,n))}function hash(t){var h=0,i;for(i=0;i<t.length;i++)h=(h*31+t.charCodeAt(i))>>>0;return h}function pick(a,n){return a[(n||G.idea.length)%a.length]}
function setStage(s){G.stage=s;$$('.stage').forEach(function(x){x.classList.toggle('active',x.getAttribute('data-stage')===s)});var order=['intake','hatch','yard','molt','arena','verdict'];$$('#route li').forEach(function(x){var a=order.indexOf(x.getAttribute('data-s')),b=order.indexOf(s);x.classList.toggle('active',a===b);x.classList.toggle('done',a<b)});window.scrollTo(0,0)}
function classify(){var t=(G.idea+' '+G.promise+' '+G.misuse).toLowerCase(),score={Fleck:0,Hand:0,Mirror:0,Teeth:0,Swarm:0,Weather:0,Burrower:0};function add(rx,k,n){if(rx.test(t))score[k]+=n}add(/kind|comfort|fun|art|music|gift|smile|compliment/,'Fleck',6);add(/build|repair|tool|work|teach|translate|help|detect|deliver|save/,'Hand',6);add(/identity|rank|status|brand|beauty|score|truth|social|profile/,'Mirror',6);add(/control|force|punish|ban|weapon|surveil|monitor|police|enemy/,'Teeth',8);add(/viral|share|everyone|trend|feed|network|meme|followers|mass/,'Swarm',7);add(/culture|society|nation|future|normal|everywhere|world|belief|public opinion/,'Weather',7);add(/maintenance|standard|number|record|archive|pipe|infrastructure|audit|filing|protocol/,'Burrower',9);if(G.food==='attention'||G.food==='status')score.Swarm+=5;if(G.food==='fear')score.Teeth+=6;if(G.food==='privacy'||G.food==='obedience')score.Teeth+=5;if(G.food==='care')score.Fleck+=5;if(G.food==='time')score.Hand+=4;G.kind=Object.keys(score).sort(function(a,b){return score[b]-score[a]})[0];var d=species[G.kind],keys=['usefulness','appetite','contagion','control','mutation'];keys.forEach(function(k,i){G.stats[k]=d.base[i]});if(G.food==='attention')G.stats.contagion+=12;if(G.food==='privacy')G.stats.control-=14;if(G.food==='money'){G.stats.usefulness+=8;G.stats.appetite+=12}if(G.food==='fear')G.stats.contagion+=14;if(G.food==='status')G.stats.mutation+=10;if(G.food==='care')G.stats.usefulness+=12;keys.forEach(function(k){G.stats[k]=clamp(G.stats[k])});G.name=pick(d.names,hash(G.idea))+' · '+G.idea.split(/[.!?]/)[0].split(' ').slice(0,5).join(' ')}
function updateStats(){Object.keys(G.stats).forEach(function(k){var v=Math.round(G.stats[k]);$('#'+k+'V').textContent=v;$('#'+k+'B').style.width=v+'%'})}
function draw(canvas,mood){if(!canvas)return;var c=canvas.getContext('2d'),w=canvas.width,h=canvas.height,d=species[G.kind],s=Math.min(w,h);c.clearRect(0,0,w,h);c.save();c.translate(w/2,h/2);var glow=c.createRadialGradient(0,0,20,0,0,s*.42);glow.addColorStop(0,'rgba(197,162,104,.18)');glow.addColorStop(1,'rgba(0,0,0,0)');c.fillStyle=glow;c.fillRect(-w/2,-h/2,w,h);c.strokeStyle='#c5a268';c.fillStyle='#6f7d79';c.lineWidth=3;var m=mood||0;if(d.shape==='storm'){for(var i=0;i<8;i++){c.beginPath();c.ellipse((i-3.5)*35,-30+(i%3)*18,70,40,0,0,Math.PI*2);c.fill()}c.strokeStyle='#d8c48d';for(i=0;i<3;i++){c.beginPath();c.moveTo(-80+i*80,15);c.lineTo(-100+i*80,90);c.lineTo(-75+i*80,82);c.lineTo(-95+i*80,145);c.stroke()}}else if(d.shape==='swarm'){for(i=0;i<24+m*5;i++){var a=i*1.7,r=30+(i%7)*18;c.beginPath();c.ellipse(Math.cos(a)*r,Math.sin(a)*r*.65,8,5,0,0,Math.PI*2);c.fill();c.stroke()}}else{c.beginPath();c.ellipse(0,35,s*.18,s*.12,0,0,Math.PI*2);c.fill();c.stroke();c.beginPath();c.arc(s*.12,-35,s*.08,0,Math.PI*2);c.fill();c.stroke();if(d.shape==='moth'){c.beginPath();c.ellipse(-s*.15,0,s*.14,s*.2,-.5,0,Math.PI*2);c.ellipse(s*.15,0,s*.14,s*.2,.5,0,Math.PI*2);c.fill();c.stroke()}else{for(i=-2;i<2;i++){c.beginPath();c.moveTo(i*45,90);c.lineTo(i*45+(i<0?-10:10),170);c.stroke()}if(d.shape==='deer'){c.beginPath();c.moveTo(25,-75);c.lineTo(55,-130);c.moveTo(40,-100);c.lineTo(75,-112);c.moveTo(5,-75);c.lineTo(-20,-130);c.stroke()}if(d.shape==='lion'){c.beginPath();c.arc(s*.12,-35,s*.13,0,Math.PI*2);c.strokeStyle='#8d4541';c.lineWidth=12;c.stroke()}}c.fillStyle='#090d10';c.beginPath();c.arc(s*.14,-45,5,0,Math.PI*2);c.fill()}c.restore()}
function setupHatch(){var d=species[G.kind];$('#specimen').textContent=G.name;$('#classLabel').textContent='CLASS '+G.kind.toUpperCase();$('#firstAction').textContent=pick(['It tests the latch before looking at its inventor.','It chooses the quietest keeper.','It watches the keys instead of the food.'],hash(G.promise));$('#desc').textContent=d.desc;$('#body').textContent=d.body;$('#appetiteOut').textContent=G.food;$('#breeding').textContent=d.breed;$('#risk').textContent=d.risk;draw($('#creature'),0);draw($('#yardCanvas'),0);draw($('#moltCanvas'),0)}
function change(arr){var keys=['usefulness','appetite','contagion','control','mutation'];keys.forEach(function(k,i){G.stats[k]=clamp(G.stats[k]+arr[i])});updateStats()}
function runTest(btn){if(btn.disabled||G.tests>=3)return;var type=btn.getAttribute('data-test');G.tests++;change(effects[type]);btn.disabled=true;btn.classList.add('used');if(G.tests===1)$('#log').innerHTML='';var p=document.createElement('p');p.innerHTML='<time>0'+G.tests+'</time>'+reactions[type][G.kind];$('#log').insertBefore(p,$('#log').firstChild);draw($('#yardCanvas'),G.tests);if(G.tests===3){$$('.test').forEach(function(x){x.disabled=true});$('#toMolt').disabled=false}}
function fix(btn){if(btn.disabled||G.fixes>=3)return;var type=btn.getAttribute('data-fix');G.fixes++;change(repairs[type]);btn.disabled=true;btn.classList.add('used');$('#remain').textContent=3-G.fixes;draw($('#moltCanvas'),G.fixes);if(G.fixes===3)$$('.intervention').forEach(function(x){x.disabled=true})}
function simulate(){if(G.done)return;G.done=true;var btn=$('#simulate'),year=0,districts=$$('.district'),seq=[2,0,3,1,4,2,3,0,4,1];btn.disabled=true;btn.textContent='Simulation running';$('#report').innerHTML='';function tick(){year++;$('#year').textContent=year;var d=districts[seq[year-1]],risk=G.stats.appetite+G.stats.contagion+G.stats.mutation-G.stats.control-G.stats.usefulness,bad=((hash(G.idea)+year*37)%100)<clamp(45+risk*.22-G.fixes*5);d.classList.add(bad?'bad':'good');setTimeout(function(){d.classList.remove('bad','good')},500);var lines=bad?['The creature begins rewarding whoever feeds it.','An emergency exception appears and never leaves.','Citizens learn to satisfy the system instead of questioning it.']:['A citizen refuses it without penalty.','A keeper catches a failure before it spreads.','The poorest district finds a smaller, better use for it.'];var p=document.createElement('p');p.innerHTML='<strong>Year '+year+'.</strong> '+lines[(year+hash(G.promise))%lines.length];$('#report').insertBefore(p,$('#report').firstChild);while($('#report').children.length>4)$('#report').removeChild($('#report').lastChild);if(year<10)setTimeout(tick,360);else setTimeout(showVerdict,650)}tick()}
function showVerdict(){var good=G.stats.usefulness+G.stats.control,bad=G.stats.appetite+G.stats.contagion+G.stats.mutation,r=good-bad,title,stamp,copy,cls='';if(G.kind==='Weather'&&r<10){title='Permanent containment';stamp='FOUR BELLS';copy='The idea has become a condition citizens may stop noticing.'}else if(r>40){title='Release into Glassmarket';stamp='ONE BELL';copy='It can work without demanding ownership of the people around it.';cls='release'}else if(r>5){title='Release with restrictions';stamp='TWO BELLS';copy='Useful enough to live. Dangerous enough to require visible limits.';cls='release'}else if(r>-35){title='Return for another molt';stamp='THREE BELLS';copy='There is something worth saving, but the creature is still too hungry or difficult to refuse.';cls='revise'}else{title='Destroy the original';stamp='FIVE BELLS';copy='The useful core cannot be separated from the harm without making a different idea.'}$('#verdictTitle').textContent=title;$('#verdictCopy').textContent=copy;$('#stamp').textContent=stamp;$('#stamp').className='stamp '+cls;$('#finalName').textContent=G.name;$('#finalClass').textContent='Class '+G.kind;$('#plateDoes').textContent=G.promise;$('#plateBenefit').textContent='Those named in the promise—and whoever holds the leash';$('#plateFeed').textContent=G.food+' supplied by '+G.refuse;$('#plateClean').textContent=G.fixes?'A named civic keeper':'Nobody has accepted responsibility';$('#plateEscape').textContent=G.misuse;draw($('#verdictCanvas'),4);setStage('verdict')}
function reset(){location.reload()}
$('#enter').onclick=function(){$('#hero').classList.add('hidden');$('#game').classList.remove('hidden');$('#caseNo').textContent=(10+Math.floor(Math.random()*89))+'-'+(100+Math.floor(Math.random()*899));setStage('intake')};
$('#idea').oninput=function(){var v=this.value;$('#chars').textContent=v.length;var smoke=/(revolutionary|game.?changing|disrupt|perfect|no downside)/i.test(v);$('#smoke').classList.toggle('warn',smoke);$('#smoke').textContent=smoke?'Yellow smoke detected. The booth thinks you are selling.':'Promotional language produces yellow smoke.'};
$('#form').onsubmit=function(e){e.preventDefault();G.idea=$('#idea').value.trim();G.promise=$('#promise').value.trim();G.refuse=$('#refuse').value.trim();G.food=$('#appetite').value;G.misuse=$('#misuse').value.trim();classify();setupHatch();updateStats();setStage('hatch')};
$('#toYard').onclick=function(){setStage('yard')};$$('.test').forEach(function(b){b.onclick=function(){runTest(b)}});$('#toMolt').onclick=function(){setStage('molt')};$$('.intervention').forEach(function(b){b.onclick=function(){fix(b)}});$('#toArena').onclick=function(){setStage('arena')};$('#simulate').onclick=simulate;$('#again').onclick=reset;$('#restartTop').onclick=reset;$('#print').onclick=function(){window.print()};
$('#sound').onclick=function(){this.textContent=this.textContent==='Sound off'?'Sound on':'Sound off'};
var sec=1112;setInterval(function(){if(G.stage!=='intake')return;sec=Math.max(0,sec-1);var m=Math.floor(sec/60),s=sec%60;$('#clock').textContent='00:'+String(m).padStart(2,'0')+':'+String(s).padStart(2,'0')},1000);updateStats();
})();
